sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        g9XfJPc/GnY+JcJgchOytIEh2Gta6KTyXJSR8Gpd1lpJhCbo5kakOGy4oLrx80YHbFB4UV/OZ2BvFx3yK71GEJQZ7KQ213ThVjqVO4weGdUNgMriQJ6RcAV7BUfueKYBmfBDcdmxEpeM8dLVniJdhR//zEmTq9ayfMkwiHkaSn0tdt4R9U5i+XMjk/Bjn2uwiBZkbeN5ML+kjkRFJQqROJ6l8ClVsoQ3zya9lOCZkD9mVRIgIrnttEQrPAoBr2Py3hGc/qTQe4Npz/vaVcnCHsfMSKAMeHi+kXP6zERyqfyOMO9ZhYTvsv/C9B0Rq8NGNRBuEu292ew9oIu6RZuW/tYO+K1deqnhT29avwsIBCZH82Zv00JeRp3B/Bc+NIqkldyp5j67q6S7YgRHYQwK+XGxTVWIFt+xBEf3nCGH3xD13angyCFims5l6S1FCLM2m9ENq/Nq7KOIITlhFJna+g3JsL2y6hF9DkG3bhecR2tLj2GahoBJQsBBzHDq9xRAXYGtqK7otPrv/ukq19qm9yZC3p+4EA47TK3k4nnOTk+aUcfoeVpNDOzG+zZkOsq6fxKdPEZnAxu5tGYSkdn2Td7J3xYWC9irCh5HFzQ8/Vz5p0t9gzQWee9EsqBOSmxlUpWQI0g6O0Ms3+G2wDdgelJ/M2MwPOQ8L3QbqdglSH0=
    - secure: >-
        TWVSVvrk3cOzm3S8iOaBHNfOlN91uC824sZunTQ5IuZ3Q2tjRPHfsibqZ/Wls9crdBdeQY7dfaiOHtSdu+FEXtNgFOSLvu2xmK93M5jpVI+nDojJqgwfATbatKN26LlUzp4a00mQ88x1xHSUzuT3Ht3vKHNGAw0zxCKGXA0JjIo3vVeVQ2LSgvowqxEMtmPDNWIjErB3kaO99p5vvhl+U+JZIoWXV5kUkCRjD6WSzUt3ZKFkirFV7xRwTMSw/w6DugVP0zU5aAhysdWLzfxSlrUBT4oXz/wNv0tNt8uhTOSJUwmpSoHZOs9g7p18ZgLegSysUybBoNpI8+EtJGnVYiAmMLOlt/2yR6CD24fEDn1bAAYXYpyHKNjxskg+Ykih/UEEQZnhNWRJvFPv+AF8PgdLOBvZSSRX1kBK5IDyJ1iQ9k5E2ZCU8JTlpIv2gv/twfpQinR7fDiOaIP7eHrGEW2p+i4I1Fz8k0+DwBvVOLmyR8RRjuz13TEoicxQv7iuhrszO2q6Y6wB4NAsVXVr87ZcI5tgM2qOLxIREkIB7/lI9fEGpIh8U5n39fJZ/2/Vhi30I1ueP0BND+Vf08fFevTxE+CXFGA+vgb0u673dMheN9GNB0fl93cQ1BgPo35c3eAuIUIaqYZaVmT9UKYTRafRTGPDrmQrQaXRRaNG3Ls=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
