sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        s15ewhWI8hURWRSoJ8V01D42r/+GGpWhSt1e3tzLOnkbHHmeQ+NHCTehEPrlw6bRyzLCuu0Gcl7fSO1hpBoKHZrfv3v8/2LYaPwb4cr9AmDDFL/uEulL/eDL54XUzG5ozt7bNDIxWczM459b9Gjcevp+5fNabHpSMY617emlrgIS4KRMIOD4Rq3oap/hmqAnGRLeY3DWhWLSqirI+OV3n/qHBwZD/hsVT1jXf1LylymGs0qiSgVB5/VSXv0JtVWly7XbkaAOs/K/L7EfcxGlxPXZ5idbux9HZunKoDb5W4LQQT6Caqwpr5bqikKb4tQ5s51ViUy98bx8lK6eREMdn3UZ7EvMqf4XrMVB9yhSEf9ldN53BDkeVse3JO2V3e6NLoDGFqWyyjabcxAsnMPLJXwOXUwVrVz/OTDBVy/t2kzXt3j7PHAmyy3ycWo6t7e+pQfl5x8sXBAqBSAjElcKS6PXYyVDg3bRE4ydwex3KLuW+5P8B5fkDcZceL7ZSfAatYVrQuevAXPsPkmEMb8OZQFSkz1zuHJ/7Fr7DSQ/VdUIKVs+inSRQn2YUMvBIGCMNazCqUD6Bv6PrQxcSk1gi0pzaRtdGKTnU+d8PE0igUb5kfAVPGcFvz1b4631rsLpSXPNNeNPmYVEYxsA8k9nqJGE54f+KJdnEvTO9+CzdEM=
    - secure: >-
        s2itb3Mgy4guWbZTzTxwNFSfBaarDLBpOlim2xVRPc1tVOGHUNh+Jasuu4jFMDa+1zUMFCWI+C/ImU775HJ6Dq07GeoXnW9fy08XxT7G8QSQKWtM5Fv3/esMZeeqlm/PuDa6tOHyZQ+4qKP7b+oVcgqnlVzpikkuZC3w/yuU0r4Cbht/hnz1mQDNiqcqDxbnpOagt9leGdaJ1ivM68jwSvt8Mi9IbhAs5Coe7SYcVJ8hhxNl3gb6q/YedgLwehAo7qffuYC9va42OTigdwykkoOabNQ4qzeuOzEqQ92QAeswwm2+Do+iUmmk0voTTJxLd/+W6k902Xf+pkoBHDon5r6wlotegFPprJpKxBwBCvSn6Cmi8MBN55vBtgRhDJpqKD5bD9fmgHnvsNIXnzInIYECKarOiocIeAKwo1B9xqpMcdeKLj1jIojdCJRuSSNN5F9Ack0KJSJ/CkiTjnue7nmTEJdsLwVEjFL7bkDm+HsGixj5T38u57nHbCqtWWe4xJyU9rSLfQkWRwhKAR9zPCmQ5XD/XJApGcSYxm51CSANAwPUiYg+OOoxyW+KVg+i0vh2ScHpKtMDiwNkgVYSiuUuwEvGo12VNF0yd7EYIrq0YM00E+oHi11/uUJZzfyI/rrIzBv7Uw/NuX1wHlPlxHo7OBFJ+aY3MRQorU3sudQ=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
