sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        OgkXP9NHoejyMsV6pc/uF5ab1+nhRWhehXCuke6oMon0txkqgMG/rfbO1a8mKvKlLDOjwEMW68sRcGu1rkojKfDwlSvWKmTqzG1z/MD/NRrFer4Er4uqBtRwf1+qx4CBdNhvsJGdqUNDR8ipkFQdnd39fyTBbWmeTQLyWKdvhLrAOwVmSgAZnpBRean+6+WgxDGZ7P09iJQ52AU06u7vgJ6eLD3N8ignfg2maYxvuawPN8NWiHCzaaD0tofSjz0ZZWbjYc9XhFGMTtII3LnDuZh0RHJBp7fisyBMYbZNBlZjY32/Gpx6KI9ccR5zv22Y4eJq1OsMSZt7IdTJHJNgRQbIjxOSMh1NFo094N8uOYUt+kNKwflj49ETHb5/RHLYkFVGX3e8fJRVROA4UndQDP1DIovkdVETt2znoTDMl8kng/60/DBi8fLEWWB8kBR68FrtfkAmpVIDfn1agZGkrt1MpZuuwK8VLPKN6FctuJ8mA3JDxYbwbeOb9FUwAR4VYBcJ02gDI/xuX8uSvywrJnkrVgBXJiaCHSQ+Xf4aJ6/tcsO4rQ4DWi3tpBFBnxXsSGLlqZasgADrb3D2mq/IXBIQRqEQ2EcMym0pwULj/W/z8dnzIyZs+UyO08gW2pSL1wM2XvD5mzscmP8vggMIB4i6gPrBMc4CwkR0H2m7EoA=
    - secure: >-
        r1o4eOVLbSVIejjuCEDTlpgqKgyNSfSu+Dr8Tbe+v2tssHMRCN7VZ/684DL4d5gZ2QFCuyfT4W1eAXQb9x5OS5bTQRMuIxzj0f4NmPbrt1XVGhu/DboVH8ntUBlla6g3lV/wQIl9rLS3RuofhVZYmMTVoIaUsui7py1AWQGorfnyRFUePxhsUVwVt0Dkel61V2mhBqndEcpUX+fq/Nt/Gf1xnb91qv67c1R0/JkgxkG63TogeESTGaEuogFxUaXFQPA498LaToXghCo8BcAvskB1ICXHvsiCzbSqHQkGFTqN+Rfbeq32OFeweSJWLt23OLFaMvhY3Av60EjcEI9w0IIzas4hXMCJFupj1rjZbDxV11MCsLX9S0zI6diARqoQgG/RHA/ZA+uEKXftBTzso8Si8aCfPEjHRvo+YaGigpfevs7qa9ZTHPXXxwofP9SlqBT+zBipHxGUR0KXFA39+UXxl0hz09RIn4Mx0ScNeif96nLCrpA4ut2/oj0DeN46/iIVCCsomx3v01ozfJhEhhbhmAM516OenJo7DI6A6wPY0JsAJriIngajnC6B3oGknyWYN190Fjw23MZtFzR1s3NwQHESAEdkuXqIWa2iuoStSq3R0HIicd/VoiVlPjZcnT1exg2fIbMo0Hj0iHxlXfOJl0BPicVX2NTNd7lIat0=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
